### ISSUE TITLE
How long I can use Restana-bun.

### ISSUE THREAD

**Issue by SaltFish001** [BackendStack21/0http-bun#2]

**Comment by SaltFish001** [comment]
![image](https://github.com/BackendStack21/0http-bun/assets/42058801/f2e41184-0920-4bc0-8aa5-acc2b157f6c4)
This is what i can do.

**Comment by SaltFish001** [comment]
Can you reWrite this lib use TypeScripts?

**Comment by jkyberneees** [comment]
Hi @SaltFish001, many thanks for supporting the project.  I will add TS types soon, but not planning to port the code to avoid performance regressions in the `sequential` router.

Quick question about your suggestion for `restana-bun`: Is your primary goal code reusability, or are you focused on maximizing performance? A significant concern with supporting Node.js interfaces lies in the potential performance degradation, especially when compared to the more efficient `Request` and `Response` objects available in Bun through `0http-bun`.

Regards

**Comment by SaltFish001** [comment]
Maybe I need learn about Bun's api. Performance first.
